#!/bin/bash

patch_rancher_monitoring_crd_chart()
{
  local chart_dir=$1 #${CHARTS_DIR}
  local monitoring_version=$2 #MONITORING_VERSION
  local pkg_monitoring_crd_path=$3 #${PKG_PATCH_MONITORING_PATH}
  local cwd=$(pwd)

  if [ ! -d "${pkg_monitoring_crd_path}/${monitoring_version}" ]; then
    echo "NOTE: there is no related path: ${pkg_monitoring_crd_path}/${monitoring_version} to patch, SKIP"
    return 0
  fi

  echo "There is no patch for rancher-monitoring-crd version ${monitoring_version}"
}
