#!/bin/bash

pull_rancher_logging_chart()
{
  local helm_repo_base_url="$1"
  local chart="$2"
  local version="${RANCHER_LOGGING_CHART_VERSION}"
  helm pull "${helm_repo_base_url}/${chart}/${chart}-${version}.tgz" -d "${CHARTS_DIR}"
  tar xzvf "${CHARTS_DIR}/${chart}-${version}.tgz" > /dev/null --warning=no-timestamp
}

patch_rancher_logging_chart()
{
  local chart_dir=$1 #${CHARTS_DIR}
  local logging_version="${RANCHER_LOGGING_CHART_VERSION}"
  local pkg_logging_path=$2 #${PKG_PATCH_LOGGING_PATH}
  local cwd=$(pwd)

  if [ ! -d "${pkg_logging_path}/${logging_version}" ]; then
    echo "NOTE: there is no related path: ${pkg_logging_path}/${logging_version} to patch, SKIP"
    return 0
  fi

  cd ${chart_dir}
  tar zxf rancher-logging-${logging_version}.tgz --warning=no-timestamp

  echo "patch rancher logging rke2 configmap.yaml, daemonset.yaml"
  cp -f ${pkg_logging_path}/${logging_version}/configmap.yaml ./rancher-logging/templates/loggings/rke2/configmap.yaml
  cp -f ${pkg_logging_path}/${logging_version}/daemonset.yaml ./rancher-logging/templates/loggings/rke2/daemonset.yaml
  grep "harvester-patch" ./rancher-logging/templates/loggings/rke2/configmap.yaml || true
  grep "harvester-patch" ./rancher-logging/templates/loggings/rke2/daemonset.yaml || true

  echo "patch rancher logging eventtailer"
  cp -f ${pkg_logging_path}/${logging_version}/eventtailer.yaml ./rancher-logging/templates/logging/eventtailer.yaml
  grep "harvester-patch" ./rancher-logging/templates/logging/eventtailer.yaml || true

  echo "patch rancher logging kube-audit fluentbitagent"
  cp -f ${pkg_logging_path}/${logging_version}/fluentbitagent.yaml ./rancher-logging/templates/loggings/kube-audit/fluentbitagent.yaml
  grep "harvester-patch" ./rancher-logging/templates/loggings/kube-audit/fluentbitagent.yaml || true

  # remove existing chart
  rm ${chart_dir}/rancher-logging-${logging_version}.tgz

  # helm pack new
  helm package rancher-logging
  rm -rf rancher-logging
  echo "finish patch ranch-logging chart"
  cd $cwd
}

test_rancher_logging_chart()
{
  local chart="$1"
  local version="${RANCHER_LOGGING_CHART_VERSION}"
  tar xzvf "${CHARTS_DIR}/${chart}-${version}.tgz" > /dev/null --warning=no-timestamp \
    && echo -e "\033[1m\033[32m${chart} PASS\033[0m" \
    || echo -e "\033[1m\033[31m${chart} FAIL\033[0m"
}
