#!/bin/bash

pull_rancher_monitoring_chart()
{
  local helm_repo_base_url="$1"
  local chart="$2"
  local version="${RANCHER_MONITORING_CHART_VERSION}"
  helm pull "${helm_repo_base_url}/${chart}/${chart}-${version}.tgz" -d "${CHARTS_DIR}"
}

patch_rancher_monitoring_chart()
{
  local chart_dir=$1 #${CHARTS_DIR}
  local monitoring_version="${RANCHER_MONITORING_CHART_VERSION}"
  local pkg_monitoring_path=$2 #${PKG_PATCH_MONITORING_PATH}
  local cwd=$(pwd)

  if [ ! -d "${pkg_monitoring_path}/${monitoring_version}" ]; then
    echo "NOTE: there is no related path: ${pkg_monitoring_path}/${monitoring_version} to patch, SKIP"
    return 0
  fi

  cd ${chart_dir}
  tar zxf rancher-monitoring-${monitoring_version}.tgz --warning=no-timestamp

  local origfile="./rancher-monitoring/charts/grafana/templates/nginx-config.yaml"
  local newfile="${pkg_monitoring_path}/${monitoring_version}/nginx-config.yaml"
  echo "patch original file $origfile"
  if [ -f "$origfile" ]; then
    ls -alth "$origfile"
    echo "diff"
    # when files are different, `diff` will return 1
    diff "$origfile" "$newfile" || true
    rm -f "$origfile"
  else
    echo "original file $origfile is not found"
  fi

  # replace grafana values busybox image version; yq can also work, but it strips all blank lines; use patch instead
  local valuesfile="./rancher-monitoring/charts/grafana/values.yaml"
  local difffile="${pkg_monitoring_path}/${monitoring_version}/patch-grafana-values.diff"
  echo "patch mirrored-library-busybox image version"
  echo "the current values.yaml has following mirrored-library-busybox image version"
  grep "mirrored-library-busybox" $valuesfile -2 || true
  if [ -f "$difffile" ]; then
    patch $valuesfile $difffile
  else
    echo "diff file $difffile is not found"
  fi
  echo "the patched values.yaml has following mirrored-library-busybox image version"
  grep "mirrored-library-busybox" $valuesfile -2 || true

  # replace with new file
  cp -f "$newfile" "$origfile"
  echo "patched file"
  ls -alth "$origfile"

  # remove existing chart
  rm -f ${chart_dir}/rancher-monitoring-${monitoring_version}.tgz

  # helm pack new
  helm package rancher-monitoring
  rm -rf rancher-monitoring
  echo "finish patch ranch-monitoring chart"
  cd $cwd
}

test_rancher_monitoring_chart()
{
  local chart="$1"
  local version="${RANCHER_MONITORING_CHART_VERSION}"
  tar xzvf "${CHARTS_DIR}/${chart}-${version}.tgz" > /dev/null --warning=no-timestamp \
    && echo -e "\033[1m\033[32m${chart} PASS\033[0m" \
    || echo -e "\033[1m\033[31m${chart} FAIL\033[0m"
}
