#!/bin/bash
set -e

# the `rancher-monitoring` and `rancher-logging` chart have some patches
# the test-chart-patch script ensure the patches can be effectively applied to target chart
# some codes are copied from https://github.com/harvester/harvester-installer/blob/1c239ed406ed0c1ec1eef37118fc54680c896bc7/scripts/build-bundle#L12

date
echo "Test chart-patch on addon path, DAPPER_SOURCE=${DAPPER_SOURCE}"

if [[ -z ${DAPPER_SOURCE} ]]; then
  echo "set the DAPPER_SOURCE env first"
  exit 1
fi

cd ${DAPPER_SOURCE}
addons_path=${DAPPER_SOURCE}

source version_info
source ./scripts/hack/patch-rancher-logging
source ./scripts/hack/patch-rancher-monitoring
source ./scripts/hack/patch-rancher-monitoring-crd

MONITORING_VERSION=${RANCHER_MONITORING_CHART_VERSION}
LOGGING_VERSION=${RANCHER_LOGGING_CHART_VERSION}
echo "Rancher monitoring version: ${MONITORING_VERSION}"
echo "Rancher logging version: ${LOGGING_VERSION}"

if [[ -z ${MONITORING_VERSION} || -z {LOGGING_VERSION} ]]; then
  echo "target chart verions are not sourced, check"
  exit 1
fi

CHARTS_DIR="${DAPPER_SOURCE}/bin/patched-charts"
mkdir -p ${CHARTS_DIR}

# Prepare monitoring chart
helm pull https://charts.rancher.io/assets/rancher-monitoring-crd/rancher-monitoring-crd-${MONITORING_VERSION}.tgz -d ${CHARTS_DIR}
helm pull https://charts.rancher.io/assets/rancher-monitoring/rancher-monitoring-${MONITORING_VERSION}.tgz -d ${CHARTS_DIR}

# patch rancher-monitoring chart to fix issues
PKG_PATCH_MONITORING_PATH="${addons_path}/pkg/config/templates/patch/rancher-monitoring"
patch_rancher_monitoring_chart ${CHARTS_DIR} ${MONITORING_VERSION} ${PKG_PATCH_MONITORING_PATH}

# patch rancher-monitoring-crd chart to fix issues
PKG_PATCH_MONITORING_CRD_PATH="${addons_path}/pkg/config/templates/patch/rancher-monitoring-crd"
patch_rancher_monitoring_crd_chart ${CHARTS_DIR} ${MONITORING_VERSION} ${PKG_PATCH_MONITORING_CRD_PATH}

# make chart sanity check
tar zxvf ${CHARTS_DIR}/rancher-monitoring-crd-${MONITORING_VERSION}.tgz >/dev/null --warning=no-timestamp
tar zxvf ${CHARTS_DIR}/rancher-monitoring-${MONITORING_VERSION}.tgz >/dev/null --warning=no-timestamp

# Prepare logging chart
helm pull https://charts.rancher.io/assets/rancher-logging-crd/rancher-logging-crd-${LOGGING_VERSION}.tgz -d ${CHARTS_DIR}
helm pull https://charts.rancher.io/assets/rancher-logging/rancher-logging-${LOGGING_VERSION}.tgz -d ${CHARTS_DIR}

# make chart sanity check
tar zxvf ${CHARTS_DIR}/rancher-logging-crd-${LOGGING_VERSION}.tgz >/dev/null  --warning=no-timestamp
tar zxvf ${CHARTS_DIR}/rancher-logging-${LOGGING_VERSION}.tgz >/dev/null --warning=no-timestamp

# patch rancher-logging chart to collect more logs"
PKG_PATCH_LOGGING_PATH="${addons_path}/pkg/config/templates/patch/rancher-logging"
patch_rancher_logging_chart ${CHARTS_DIR} ${LOGGING_VERSION} ${PKG_PATCH_LOGGING_PATH}

# make chart sanity check again after patch
tar zxvf ${CHARTS_DIR}/rancher-logging-${LOGGING_VERSION}.tgz >/dev/null --warning=no-timestamp

echo "the patched chart files"
ls ${CHARTS_DIR} -alt

echo "PASS"
